export const state = () => ({
  header: [
    'name',
    'day1',
    'day2',
    'day3',
    'day4',
    'day5',
    'day6',
    'day7',
    'day8',
    'day9',
    'day10',
    'day11',
    'day12',
    'day13',
    'day14',
    'day15',
    'day16',
    'day17',
    'day18',
    'day19',
    'day20',
    'day21',
    'day22',
    'day23',
    'day24',
    'day25',
    'day26',
    'day27',
    'day28',
    'day29',
    'day30'
  ],
  schedule1: [
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    }
  ],
  schedule: [
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Muhammad Nando Hidayat Muhammad Nando Hidayat',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Laksita Kusuma Wardhani',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Yulia Dini Hakiki',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Raissa Almira Rachmayanti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    },
    {
      name: 'Lidya Puji Astuti',
      day1: undefined,
      day2: undefined,
      day3: undefined,
      day4: undefined,
      day5: undefined,
      day6: undefined,
      day7: undefined,
      day8: undefined,
      day9: undefined,
      day10: undefined,
      day11: undefined,
      day12: undefined,
      day13: undefined,
      day14: undefined,
      day15: undefined,
      day16: undefined,
      day17: undefined,
      day18: undefined,
      day19: undefined,
      day20: undefined,
      day21: undefined,
      day22: undefined,
      day23: undefined,
      day24: undefined,
      day25: undefined,
      day26: undefined,
      day27: undefined,
      day28: undefined,
      day29: undefined,
      day30: undefined
    }
  ],
  shift: [
    {
      id: 1,
      kode: 'P'
    },
    {
      id: 2,
      kode: 'S'
    },
    {
      id: 3,
      kode: 'M'
    }
  ],
  weekend: [5, 12, 19, 26],
  holiday: [10, 12]
})

export const mutations = {
  updateSchedule(state, { staff, day, shift }) {
    if (day.length === 1) {
      state.schedule[staff]['day' + day[0]] = shift
    } else {
      for (let i = day[0]; i <= day[1]; i++) {
        state.schedule[staff]['day' + i] = shift
      }
    }
  }
}
